sudo: required

services:
- docker

language: go

go:
- 1.x

go_import_path: github.com/criteo/graphite-remote-adapter

script:
- make style test
# verify front-end is up to date.
- make clean assets
- make mod-tidy
- git diff --exit-code

before_deploy:
- make promu
- promu crossbuild
- promu crossbuild tarballs
- promu checksum .tarballs

deploy:
  provider: releases
  api_key:
    secure: dMi/ghTZAgzShxMdQPJdnFAq7Mhu34uUF+6uRSESxAE0O2rAee217LYCU9Gkhx/xZzQvgauFOG2sDjrok9g3DAIw64dVJk3ciFwgK2DN0TIesVAKxqGK9JTIJlZCmkbS3Ez30HYHggMjJVWjk0i0NYe4PObYsywOsvhedRMqvQeSWie4OPv0StIcwFWm2fFsZEXcHwazPhT7JIpIcfNhbcbWLsL6oe90vPnfnp1Ipud/165zxnL7Ny5+6b7EB2wnIt+GfcpytDzzLPJhhqFwvUmwOMM52Scw1CrUWWbipCCeOMgPDdHBONstukErMnsEVocdLoKG/taSdse4O523gXzI59Rg6ok1uUvRcWWU2nS6CZNkam0Pv3GfAa58D5Bpu1xtaMnkZXEYMBUocSu80h9QwoBEo4iF7LbyGmvwIOThAllG/vBa6ln5YfYOVHbV++RF3llw+8qjeHbMUR7osaburtdd4KKlTo/9MtHcFK6lBCYNpBDcRmajCjeVbEI58xwdzF0bephvn4hZUa9J2k0CSo6CkU+l9JTB2QUwSvJx5EyuiuIwoKCbKej7LTa6LvSxIh6gNMcj477iaQAnIttTVSwNMQO4bqQ1Id9qmnHshZWMRYLlb2YdCvUKm8PCHZIzZzM9Z3vdimFZuRkN58JSBo6q9PVhWPC9Lxn735E=
  file_glob: true
  file: .tarballs/*
  skip_cleanup: true
  on:
    tags: true
